apiVersion: v1                    
kind: Namespace
metadata:
  name: policies-postconfig-deploy                             
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: deploy-simple-deploy-cluster-postconfig-policies
  namespace: policies-postconfig-deploy
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - deploy-simple-deploy-cluster-postconfig-policies
---
apiVersion: v1                      
kind: Namespace
metadata:
  name: ggithubcom-alekonko-do480-gitops-policy-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
  name: ggithubcom-alekonko-do480-gitops-policy
  namespace: ggithubcom-alekonko-do480-gitops-policy-ns
spec:
  type: Git
  pathname: 'https://github.com/alekonko/do480-gitops-policy.git'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: 
    apps.open-cluster-management.io/git-path: simple-deploy/
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: deploy-simple-deploy-cluster-postconfig-policies
  name: deploy-simple-deploy-cluster-postconfig-policies-subscription-1
  namespace: policies-postconfig-deploy
spec:
  channel: ggithubcom-alekonko-do480-gitops-policy-ns/ggithubcom-alekonko-do480-gitops-policy
  placement:
    placementRef:
      kind: PlacementRule
      name: deploy-postconfig-policies-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: deploy-simple-deploy-cluster-postconfig-policies
  name: deploy-simple-deploy-cluster-postconfig-policies-placement-1
  namespace: policies-postconfig-deploy
spec:
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'
