---
apiVersion: v1
kind: Namespace
metadata:
  name: policies-postconfig-deploy                
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
  name: do480-gitops-policy
  namespace: policies-postconfig-deploy
spec:
  type: Git
  pathname: 'https://github.com/alekonko/do480-gitops-policy.git'
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: deploy-postconfig
  namespace: policies-postconfig-deploy
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - policies-postconfig-deploy
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: 
    apps.open-cluster-management.io/git-path: simple-deploy/
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: policies-postconfig-deploy
  name: policies-postconfig-deploy-subscription
  namespace: policies-postconfig-deploy
spec:
  channel: do480-gitops-policy/policies-postconfig-deploy
  placement:
    placementRef:
      kind: PlacementRule
      name: deploy-postconfig-policies-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: policies-postconfig-deploy
  name: policies-postconfig-deploy-placement
  namespace: policies-postconfig-deploy
spec:
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'
