apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-operators
spec:
  channel: stable
  name: openshift-gitops-operator
  # source: redhat-operators
  source: do480-catalog
  sourceNamespace: openshift-marketplace
